---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: Puede configurar NetApp Workload Factory para enviar notificaciones a una persona u otra aplicación cuando ocurren determinados tipos de eventos. 
---
= Configurar las notificaciones de NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Puede configurar el servicio de notificaciones de NetApp Workload Factory para enviar notificaciones como alertas en la consola de NetApp o en un tema de Amazon SNS.  Las notificaciones enviadas como alertas aparecen en la consola de NetApp cuando tiene un agente o un enlace de consola implementado.  Cuando Workload Factory publica notificaciones en un tema de Amazon SNS, los suscriptores del tema (como personas u otras aplicaciones) reciben las notificaciones en los puntos finales configurados para el tema (como mensajes de correo electrónico o SMS).



== Tipos de notificaciones y mensajes

Workload Factory envía notificaciones para los siguientes eventos:

[cols="6*"]
|===
| Evento | Descripción | Tipo de notificación | Gravedad | Carga de trabajo | Tipo de recurso 


| Algunas instancias de bases de datos en su cuenta no tienen una buena arquitectura | Se han analizado todas las instancias de Microsoft SQL Server en su cuenta para detectar problemas bien diseñados.  La descripción de este evento proporciona la cantidad de instancias bien diseñadas e instancias no optimizadas.  Revise los hallazgos y recomendaciones de estado bien diseñados en el inventario de bases de datos desde la consola de Workload Factory. | Bien diseñado | Recomendación | Oracle | Instancia de Microsoft SQL Server 


| Implementación exitosa del servidor Microsoft SQL Server/PostgreSQL | La implementación del host de Microsoft SQL Server o PostgreSQL se realizó correctamente. Para obtener más información, consulte la sección sobre supervisión de trabajos. | Puesta en marcha | Correcto | Oracle | FSx para ONTAP, host de base de datos 


| Error en la implementación del servidor Microsoft SQL Server/PostgreSQL | Se produjo un error en la implementación del host de Microsoft SQL Server o PostgreSQL. Para obtener más información, consulte la sección sobre supervisión de trabajos. | Puesta en marcha | Error | Oracle | FSx para ONTAP, host de base de datos 


| Falló la creación de la relación de replicación | Ha fallado la creación de una relación de replicación de SnapMirror .  Para obtener más información, vaya a Rastreador. | Replicación | Crítico | Almacenamiento general | FSx para ONTAP 


| Error en la creación de FSx para ONTAP | Ha fallado un proceso de creación del sistema de archivos FSx para ONTAP .  Para obtener más información, vaya a Rastreador. | Acción del sistema de archivos FSx para ONTAP | Crítico | Almacenamiento general | FSx para ONTAP 


| La capacidad SSD automática o los inodos aumentan el éxito | Durante una reciente actualización de administración de capacidad automática, el sistema de archivos FSx para ONTAP aumentó la capacidad SSD o los inodos de volumen con éxito. Para obtener más información, vaya a Rastreador. | Gestión de la capacidad | Correcto | Almacenamiento general | FSx para archivos ONTAP 


| Falla automática en el aumento de capacidad del SSD o de los inodos | Durante una reciente actualización de administración de capacidad automática, el sistema de archivos FSx para ONTAP no pudo aumentar la capacidad SSD ni los inodos de volumen. Para obtener más información, vaya a Rastreador. | Gestión de la capacidad | Crítico | Almacenamiento general | FSx para sistemas de archivos ONTAP 


| Se detectó un problema con FSx para ONTAP | Se han analizado todos los sistemas de archivos FSx para ONTAP para detectar problemas de buena arquitectura.  El análisis detectó uno o más problemas.  Para obtener más información, revise el análisis bien diseñado desde el panel de Almacenamiento en la consola de Workload Factory. | Análisis bien diseñado | Recomendación | Almacenamiento general | FSx para sistemas de archivos ONTAP 


| Evento de gestión automática de capacidad para FSx para ONTAP | El nivel de rendimiento SSD para el sistema de archivos FSx para ONTAP alcanzó el umbral de advertencia de capacidad/porcentaje total. | Gestión de la capacidad | Advertencia | Almacenamiento general | FSx para sistemas de archivos ONTAP 


| Evento de gestión automática de inodos para FSx para ONTAP | El recuento de inodos para el volumen FSx para ONTAP alcanzó el umbral de advertencia de recuento/porcentaje total. | Gestión de la capacidad | Advertencia | Almacenamiento general | FSx para sistemas de archivos ONTAP 
|===


== Configurar las notificaciones de Workload Factory

Configure las notificaciones de Workload Factory mediante la consola de NetApp o la consola de Workload Factory.  Si usa la consola de NetApp , puede configurar Workload Factory para enviar notificaciones como alertas en la consola de NetApp o a un tema de Amazon SNS.  Puede configurar notificaciones desde la *Configuración de notificaciones* en la consola de NetApp .

.Antes de empezar
* Debe configurar Amazon SNS y crear temas de Amazon SNS mediante la consola de Amazon SNS o la AWS CLI.
* Tenga en cuenta que Workload Factory admite el tipo de tema *Estándar*.  Este tipo de tema no garantiza que las notificaciones se envíen a los suscriptores en el orden en que se recibieron, así que considere esto si tiene notificaciones críticas o de emergencia.


[role="tabbed-block"]
====
.Configurar notificaciones desde la consola de NetApp
--
.Pasos
. Iniciar sesión en ellink:https://console.netapp.com["Consola de NetApp"^] .
. Desde el menú de la consola de NetApp , seleccione *Cargas de trabajo*, *Administración* y, luego, *Configuración de notificaciones*.
. En la página de configuración de notificaciones, haga lo siguiente:
+
.. Opcional: seleccione *Habilitar notificaciones de la consola de NetApp * para configurar Workload Factory para que envíe notificaciones en la consola de NetApp .
.. Seleccione *Habilitar notificaciones SNS*.
.. Siga las instrucciones para configurar Amazon SNS desde la consola de Amazon SNS.
+
Después de crear el tema, copie el ARN del tema e ingréselo en el campo *ARN del tema SNS* en la página *Configuración de notificaciones*.



. Después de verificar la configuración enviando una notificación de prueba, seleccione *Aplicar*.


.Resultado
Workload Factory está configurado para enviar notificaciones al tema de Amazon SNS que usted especificó.

--
.Configurar notificaciones desde la consola de Workload Factory
--
.Pasos
. Iniciar sesión en ellink:https://console.workloads.netapp.com["Consola de Workload Factory"^] .
. Desde el menú de la consola de Workload Factory, seleccione *Cargas de trabajo*, *Administración* y luego *Configuración de notificaciones*.
. Seleccione *Habilitar notificaciones SNS*.
. Siga las instrucciones para configurar Amazon SNS desde la consola de Amazon SNS.
. Después de verificar la configuración enviando una notificación de prueba, seleccione *Aplicar*.


.Resultado
Workload Factory está configurado para enviar notificaciones al tema de Amazon SNS que usted especificó.

--
====


== Suscríbete al tema de Amazon SNS

Después de configurar Workload Factory para enviar notificaciones a un tema, siga las https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["instrucciones"] en la documentación de Amazon SNS para suscribirse al tema para poder recibir notificaciones de Workload Factory.



== Filtrar notificaciones

Puede reducir el tráfico de notificaciones innecesarias y orientar tipos de notificaciones específicos para usuarios específicos aplicando filtros a las notificaciones.  Puede hacerlo mediante una política de Amazon SNS para notificaciones de SNS y mediante la configuración de notificaciones en la consola de NetApp .



=== Filtrar notificaciones de Amazon SNS

Cuando te suscribes a un tema de Amazon SNS, recibes todas las notificaciones publicadas en ese tema de forma predeterminada.  Si desea recibir solo notificaciones específicas del tema, puede utilizar una política de filtro para controlar qué notificaciones recibe.  Las políticas de filtro hacen que Amazon SNS envíe únicamente las notificaciones que coinciden con la política de filtro al suscriptor.

Puede filtrar las notificaciones de Amazon SNS según los siguientes criterios:

[cols="3*"]
|===
| Descripción | Nombre del campo de política de filtro | Valores posibles 


| Tipo de recurso | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| Carga de trabajo | `workload` | `WLMDB` 


| Prioridad | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| Tipo de notificación | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.Pasos
. En la consola de Amazon SNS, edite los detalles de suscripción para el tema de SNS.
. En el área *Política de filtro de suscripción*, seleccione filtrar por *Atributos del mensaje*.
. Habilite la opción *Política de filtro de suscripciones*.
. Introduzca una política de filtro JSON en el cuadro *Editor JSON*.
+
Por ejemplo, la siguiente política de filtro JSON acepta notificaciones del recurso Microsoft SQL Server que están relacionadas con la carga de trabajo WLMDB, tienen una prioridad de Éxito o Error y brindan detalles sobre el estado de buena arquitectura:

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. Seleccione *Guardar cambios*.


Para conocer otros ejemplos de políticas de filtrado, consulte https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Políticas de filtro de ejemplo de Amazon SNS"^] .

Para obtener más información sobre la creación de políticas de filtros, consulte la https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Documentación de Amazon SNS"^] .



=== Filtrar notificaciones en la consola de NetApp

Puede utilizar la configuración de notificaciones de la consola de NetApp para filtrar las notificaciones que recibe en la consola por nivel de gravedad, como Crítico, Información o Advertencia.

Para obtener más información sobre cómo filtrar notificaciones en la consola, consulte la https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["Documentación de la consola de NetApp"^] .
