---
sidebar: sidebar 
permalink: console-experiences.html 
keywords: console, consoles, access, saas, Workload Factory, NetApp Workload Factory, NetApp Console 
summary: Se puede acceder a NetApp Workload Factory a través de dos consolas basadas en web. 
---
= Experiencias de consola
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Se puede acceder a NetApp Workload Factory a través de dos consolas basadas en web.  Aprenda cómo acceder a Workload Factory mediante la consola de Workload Factory y la consola de NetApp .

* *Consola NetApp *: ofrece una experiencia híbrida donde puede administrar sus sistemas de archivos FSx para ONTAP y cargas de trabajo que se ejecutan en Amazon FSx for NetApp ONTAP en el mismo lugar.
* *Consola Workload Factory*: ofrece una experiencia de Workload Factory dedicada y enfocada en cargas de trabajo que se ejecutan en Amazon FSx for NetApp ONTAP.




== Acceda a Workload Factory en la consola de NetApp

Puede acceder a Workload Factory desde la NetApp Console. Además de utilizar Workload Factory para las capacidades de almacenamiento y carga de trabajo de AWS, también puede acceder a otros servicios de datos como NetApp Copy and Sync y más.

.Pasos
. Iniciar sesión en ellink:https://console.netapp.com["Consola de NetApp"^] .
. Desde el menú de la consola de NetApp , seleccione *Cargas de trabajo* y luego *Descripción general*.




== Acceda a Workload Factory en la consola de Workload Factory

Puede acceder a Workload Factory desde la consola de Workload Factory.

.Paso
. Iniciar sesión en ellink:https://console.workloads.netapp.com["Consola de Workload Factory"^] .

