---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factory escanea las configuraciones de carga de trabajo en busca de confiabilidad, seguridad, excelencia operativa, optimización de costos y eficiencia del rendimiento, brindando información y recomendaciones para ayudarlo a lograr la excelencia operativa. 
---
= Crea y opera cargas de trabajo bien diseñadas con NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory, la suite de gestión NetApp para Amazon FSx for NetApp ONTAP, te ayuda a mantener y operar configuraciones de cargas de trabajo fiables, seguras, eficientes y rentables que se alinean con el AWS Well-Architected Framework. Workload Factory proporciona análisis diario de tus cargas de trabajo, recomendaciones y correcciones automáticas para promover operaciones saludables de las cargas de trabajo. Al automatizar este proceso, Workload Factory minimiza el error humano y asegura la coherencia en la gestión de las cargas de trabajo.



== Cómo funciona

Workload Factory analiza tus cargas de trabajo que se ejecutan diariamente en Amazon FSx for NetApp ONTAP file systems deployments. El análisis proporciona estado bien arquitectado, información y recomendaciones.

Una vez completado el análisis diario, las configuraciones aparecen como "optimizadas" o "no optimizadas" en el panel de control de buena arquitectura para la implementación. Encontrará la puntuación de optimización total, los problemas de configuración por categoría y una lista de problemas de configuración y recomendaciones. Puede revisar las recomendaciones para problemas de configuración. Algunos problemas pueden solucionarse automáticamente mediante Workload Factory, mientras que otros requieren intervención manual. En este caso, Workload Factory proporciona instrucciones detalladas para ayudarle a implementar los cambios recomendados.

Puedes descartar el análisis de configuraciones que no se aplican a tus entornos. Esto evita alertas innecesarias y resultados de optimización imprecisos. Cuando descartas el análisis de una configuración específica, Workload Factory no incluye la configuración en la puntuación total de optimización.



== Por qué es importante

Workload Factory aplica las mejores prácticas a grandes entornos de almacenamiento, bases de datos y VMware combinando la evaluación continua con recomendaciones y correcciones. Las correcciones automatizadas aplicadas en la consola de Workload Factory reducen los errores humanos, garantizan una gestión uniforme y preservan el rendimiento y la fiabilidad en todas tus infraestructuras de cargas de trabajo.



== Empieza con Workload Factory para detectar y corregir errores de configuración en las cargas de trabajo

Para comenzar con Workload Factory, regístrate, agrega credenciales y establece conectividad para administrar recursos de AWS y optimizar cargas de trabajo usando Amazon FSx for NetApp ONTAP.

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["Inicio rápido"]



== Información relacionada

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementar FSx bien diseñado para sistemas de archivos ONTAP"^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar cargas de trabajo de bases de datos bien diseñadas"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Implementa configuraciones de EVS bien diseñadas"^]

