---
sidebar: sidebar 
permalink: whats-next.html 
keywords: what you can do 
summary: Una vez que haya iniciado sesión y configurado NetApp Workload Factory, podrá crear y administrar sistemas de archivos FSx para ONTAP y utilizar otras capacidades de Workload Factory. 
---
= Optimice las cargas de trabajo con NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Una vez que haya iniciado sesión y configurado NetApp Workload Factory, puede comenzar a usar varias capacidades de Workload Factory, como la creación de sistemas de archivos de Amazon FSx para ONTAP , la implementación de bases de datos en sistemas de archivos de FSx para ONTAP y la migración de configuraciones de máquinas virtuales a VMware Cloud on AWS usando sistemas de archivos de FSx para ONTAP como almacenes de datos externos.

* https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Amazon FSX para ONTAP de NetApp"^]
+
Evalúa y analiza el estado de los datos actuales para ahorrar posibles costes usando FSx para ONTAP como infraestructura de almacenamiento, aprovisiona y templatiza las implementaciones de FSx para ONTAP basadas en prácticas recomendadas y accede a funcionalidades de gestión avanzadas.

* https://docs.netapp.com/us-en/workload-databases/index.html["Cargas de trabajo de base de datos"^]
+
Detecta el estado de tus bases de datos actuales en AWS, evalúa el posible ahorro en costes cambiando a FSx para ONTAP, pon en marcha bases de datos integrales con prácticas recomendadas incorporadas para la optimización y automatiza la clonación ligera para las canalizaciones de CI/CD.

* https://docs.netapp.com/us-en/workload-genai/index.html["GenAI"^]
+
Implemente y gestione una infraestructura de generación aumentada de recuperación (RAG) para mejorar la precisión y la singularidad de sus aplicaciones de IA. Crea una base de conocimientos de RAG en FSx para ONTAP con seguridad de datos y cumplimiento normativo integrados.

* https://docs.netapp.com/us-en/workload-vmware/index.html["Cargas de trabajo de"^]
+
Simplifique las migraciones y las operaciones con recomendaciones inteligentes y soluciones automáticas. Ponga en marcha backups eficientes y una sólida recuperación ante desastres. Supervise sus máquinas virtuales y solucione problemas.

* https://docs.netapp.com/us-en/workload-eda/index.html["Cargas de trabajo de EDA"^]
+
Optimice FSx para ONTAP en múltiples sistemas de archivos para mejorar el rendimiento y reducir los costos operativos mediante la gestión automatizada de parámetros de almacenamiento.


